### ISSUE TITLE
V2 版本是 2.1.8 吗？

### ISSUE THREAD

**Issue by sfjnjau** [jedmeng/python-konkeio#5]
这个V2版本修复了IR/RF学码BUG，请问与“射频码只能保存一个”有关吗？另外，好像只找到pykonkeio (2.1.7)  - Python library for interfacing with konke smart appliances，没有 2.1.8啊
https://pypi.org/project/pykonkeio

**Comment by sfjnjau** [comment]
RF学码问题解决：找到文件.../lib/python3.7/site-packages/pykonkeio/mixin/ir.py

"""
        删除射频信号
"""
    async def rf_remove(self, rf_id, group=DEFAULT_GROUP):
        if self.is_support_rf:
            cmd = 'operate#3035#deletekey#%s#%s' % (group, rf_id)
            await self.send_message(cmd, 'uart')

推测作者此处手抖，写成了“delete”，这样会删除整个默认组，即所有rf_id。

**Comment by Stream-z** [comment]
感谢提供的信息，搜了好久，完美解决了这个问题
